name: Build Fund Status Index

on:
  schedule:
    # Runs every day at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  build-index:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install axios
      
      - name: Build fund status index
        run: node scripts/buildFundIndex.js
        env:
          NODE_ENV: production
      
      - name: Upload to Vercel Blob
        env:
          BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
        run: |
          npm install @vercel/blob
          node scripts/uploadToBlob.js
      
      - name: Commit index file (backup)
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/fund-status.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update fund status index [skip ci]"
          git push
